import type { Metadata } from 'next'
import './globals.css'

import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="font-pp-mori">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
